Repository vaadin/platform, pull requests merged in 2019-10, with the labels that each got.

#881 Maintenance release notes for 14.1
  scripts/generator/generate.js
  scripts/generator/templates/template-release-notes-maintenance.md
Labels: v14.1

#879 Maintenance release notes for 14.0
  scripts/generator/generate.js
  scripts/generator/templates/template-release-notes-maintenance.md
Labels: v14

#883 Add Vaadin Router to the platform
  README.md
  scripts/generator/templates/template-release-notes.md
  scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json
  versions.json
Labels: ccdm, v15

#888 Set clientSideMode to be false in platform tests
  vaadin-platform-test/pom-bower.xml
  vaadin-platform-test/pom.xml
Labels: ccdm

#899 Update @vaadin/vaadin-router to 1.5.0
  versions.json
Labels: ccdm

#910 Upgrade flow version to 2.1.0.beta3
  versions.json
Labels: v14.1
