Repository vaadin/platform, pull requests merged in 2019-01, with the labels that each got.

#496 Update shadycss version
  scripts/generator/templates/template-vaadin-bom.xml
  versions.json
Labels: v13

#497 Update shadycss version
  scripts/generator/templates/template-vaadin-bom.xml
  versions.json
Labels: v12

#421 Verify bower dependencies pr v10
  .travis.yml
  scripts/verifyBowerDependencies.sh
Labels: testing

#456 Verify npm dependencies
  .travis.yml
  scripts/generator/templates/template-vaadin-core-package.json
  scripts/generator/templates/template-vaadin-package.json
  scripts/verifyNpmDependencies.sh
Labels: testing
