Repository vaadin/platform, pull requests merged in 2019-09, with the labels that each got.

#821 Update Spring addon to 12.0.4
  versions.json
Labels: v14

#816 Flow version to 2.1.0.alpha1
  versions.json
Labels: v14.1

#815 Add entry point files for `vaadin` npm and bower artifacts
  scripts/generator/templates/template-vaadin-bower.json
  scripts/generator/templates/template-vaadin-package.json
Labels: v14, v14.1, v15

#827 Bump to Flow 3.0.0.alpha1
  versions.json
Labels: v15

#834 Updated Flow to 2.0.10
  versions.json
Labels: v14

#839 Bump component versions
  versions.json
Labels: v14

#844 Bump component versions
  versions.json
Labels: v14

#863 Add flow dnd to the platform
  scripts/generator/templates/template-vaadin-spring-bom.xml
  vaadin-core/pom.xml
Labels: v14.1, v15

#878 Update versions of components
  versions.json
Labels: v14
