Repository vaadin/platform, pull requests merged in 2021-09, with the labels that each got.

#2375 Bump ce to 3.2.0 (master)
  versions.json
Labels: target/21.0

#2398 chore: update release note template for 14.7+ [skip ci]
  scripts/generator/templates/template-release-notes.md
Labels: target/14.8

#2393 chore: fix links in release note [skip ci]
  scripts/generator/templates/template-release-notes.md
Labels: target/21.0

#2403 Bump CE to 3.2.1
  versions.json
Labels: target/21.0

#2412 chore: update maintenance releasenote [skip ci]
  scripts/generator/templates/template-release-notes-maintenance.md
Labels: target/20.0, target/21.0
