Repository vaadin/platform, pull requests merged in 2021-07, with the labels that each got.

#2236 chore: ignore warning lines when running in a docker container [skip ci]
  scripts/generateBoms.sh
Labels: target/14.6, target/14.7, target/20.0

#2240 Do not download webdriver when using sauce or selenium hub
  vaadin-platform-gradle-test/src/test/java/com/vaadin/platform/gradle/test/AbstractPlatformTest.java
  vaadin-platform-gradle-test/src/test/java/com/vaadin/platform/gradle/test/HelloVaadinerIT.java
  vaadin-platform-hybrid-test/pom.xml
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeDeviceTest.java
  vaadin-platform-test/pom.xml
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/AbstractPlatformTest.java
Labels: target/14.6, target/14.7, target/20.0

#2264 chore: Update slf4j to 1.7.32
  scripts/generator/templates/template-vaadin-bom.xml
Labels: target/14.7, target/20.0, target/21.0

#2265 Fix: Point to start.vaadin.com
  scripts/generator/templates/template-release-notes-maintenance.md
Labels: target/14.7, target/20.0, target/21.0

#2266 Chore: update ci-sauce plugin version
  vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
Labels: target/20.0, target/21.0

#2276 test: forward grid.browsers parameter (14.x)
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/14.7

#2275 test: forward grid.browsers parameter
  vaadin-platform-test/pom.xml
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/20.0, target/21.0
