Repository vaadin/platform, pull requests merged in 2021-02, with the labels that each got.

#1810 test: add missing components to smoke tests.
  vaadin-platform-test/pom.xml
  vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java
  vaadin-platform-test/src/main/java/com/vaadin/platform/test/Entity.java
  vaadin-platform-test/src/main/java/com/vaadin/platform/test/Log.java
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentUsageTest.java
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/14.5, target/18.0

#1820 chore: fix cherry-pick script
  scripts/cherryPick.js
Labels: target/14.4, target/14.5, target/18.0

#1852 add offline test
  .gitignore
  pom.xml
  vaadin-platform-hybrid-test/.npmrc
  vaadin-platform-hybrid-test/frontend/index.html
  vaadin-platform-hybrid-test/frontend/index.ts
  vaadin-platform-hybrid-test/frontend/routes.ts
  vaadin-platform-hybrid-test/frontend/themes/fusion-test/styles.css
  vaadin-platform-hybrid-test/frontend/themes/fusion-test/theme.json
  vaadin-platform-hybrid-test/frontend/views/helloworld/hello-world-view.css
  vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.ts
  vaadin-platform-hybrid-test/frontend/views/main/main-view.ts
  vaadin-platform-hybrid-test/frontend/views/view.ts
  vaadin-platform-hybrid-test/pom-dev-mode.xml
  vaadin-platform-hybrid-test/pom.xml
  vaadin-platform-hybrid-test/src/main/java/com/vaadin/platform/fusion/test/Application.java
  vaadin-platform-hybrid-test/src/main/java/com/vaadin/platform/fusion/test/views/helloworld/HelloWorldView.java
  vaadin-platform-hybrid-test/src/main/resources/META-INF/resources/icons/icon.png
  vaadin-platform-hybrid-test/src/main/resources/META-INF/resources/images/logo.png
  vaadin-platform-hybrid-test/src/main/resources/application.properties
  vaadin-platform-hybrid-test/src/main/resources/banner.txt
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeDeviceTest.java
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ChromeOfflineIT.java
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/SauceLabsHelper.java
  vaadin-platform-hybrid-test/types.d.ts
Labels: fusion

#1870 chore: do not activate test profiles by default
  pom.xml
Labels: target/14.4
