Repository vaadin/platform, pull requests merged in 2021-08, with the labels that each got.

#2292 Fix getting started release notes section for prereleases
  scripts/generator/templates/template-release-notes-prerelease.md
Labels: target/14.7, target/21.0

#2312 test: test latest safari
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/21.0

#2320 chore:remove travis
  .travis.yml
Labels: target/14.6, target/20.0, target/14.7, target/21.0

#2324 chore: remove travis [skip ci] (CP:14.6)
  .travis.yml
Labels: target/14.7

#2325 Updates to the release notes templates [skip ci]
  scripts/generator/templates/template-release-notes-maintenance.md
  scripts/generator/templates/template-release-notes-prerelease.md
  scripts/generator/templates/template-release-notes.md
Labels: target/20.0, target/21.0

#2366 chore: use fixed webdriver manager
  vaadin-platform-hybrid-test/pom.xml
  vaadin-platform-test/pom.xml
Labels: target/20.0, target/21.0
