Repository vaadin/platform, pull requests merged in 2021-04, with the labels that each got.

#2009 fix: do not use bower register, exclude non bower components
  scripts/generator/src/creator.js
Labels: target/14.5

#2010 fix: do not prefix non-vaadin elements [skip ci]
  scripts/generator/src/creator.js
Labels: target/14.5

#2014 chore: update cherrypick bot to post comment
  scripts/cherryPick.js
Labels: target/14.5, target/14.6, target/19.0

#2054 chore: replace version with the appropiate value in vaadin_versions.json
  vaadin-core/pom.xml
Labels: target/14.5, target/14.6, target/19.0

#2066 Chore: add webdriver dependency
  platform-servlet-containers-tests/pom.xml
Labels: target/20.0
