Repository vaadin/platform, pull requests merged in 2021-03, with the labels that each got.

#1894 chore: update license to CVDL 4.0
  README.md
  scripts/generator/templates/template-vaadin-package.json
  scripts/generator/templates/template-vaadin-shrinkwrap-package.json
Labels: cherry-picked-19.0, target/19.0

#1872 test: add test for global css loader
  vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.global.css
  vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.ts
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/cssloader/CssLoaderIT.java
Labels: fusion

#1909 test: add tests for fusion with all vaadin elements
  .gitignore
  vaadin-platform-hybrid-test/frontend/routes.ts
  vaadin-platform-hybrid-test/frontend/views/components/components-view.ts
  vaadin-platform-hybrid-test/frontend/views/main/main-view.ts
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/offline/ComponentsIT.java
  vaadin-platform-hybrid-test/types.d.ts
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentUsageTest.java
Labels: target/18.0, target/19.0

#1924 Revert "test: add test for global css loader (#1872)"
  vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.global.css
  vaadin-platform-hybrid-test/frontend/views/helloworldts/hello-world-ts-view.ts
  vaadin-platform-hybrid-test/src/test/java/com/vaadin/platform/fusion/cssloader/CssLoaderIT.java
Labels: fusion

#1949 Update license checker version
  versions.json
Labels: target/14.6

#1950 fix: fix build with jdk-16
  pom.xml
Labels: target/19.0

#1982 Remove non-existing module from Vaadin 15+
  scripts/generator/templates/template-vaadin-spring-bom.xml
Labels: target/19.0
