Repository vaadin/platform, pull requests merged in 2022-11, with the labels that each got.

#3434 chore: Update TB to latest for 23
  versions.json
Labels: target/23.2

#3447 chore: update gretty version
  vaadin-platform-gradle-test/build.gradle
Labels: target/23.2

#3470 chore: remove the pinned commons-io dependency [skip ci]
  scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
Labels: target/23.1, target/23.2, target/23.3

#3469 chore: Upgrade license checker to 1.11.1
  versions.json
Labels: target/14.8, target/22.0, target/23.1, target/23.2, target/23.3

#3487 chore: Upgrade license checker to 1.11.2
  versions.json
Labels: target/23.2, target/23.3, target/14.9

#3510 update: OSGi to 8.0.3
  versions.json
Labels: target/23.1, target/23.2

#3514 chore: Update to TB 8.1.4
  versions.json
Labels: target/23.2

#3515 chore: Remove flow-polymer-template from vaadin-core
  vaadin-core/pom.xml
Labels: v24
