Repository vaadin/platform, pull requests merged in 2022-06, with the labels that each got.

#3012 chore: Update TB version
  versions.json
Labels: target/23.0, target/23.1

#3026 chore: upgrade testbench to 8.0.2
  versions.json
Labels: target/master, target/23.1

#3029 chore: filter out one more warning
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ChromeComponentsIT.java
Labels: target/23.1

#3030 chore: remove NOTE section in 23.0 [skip ci]
  scripts/generator/templates/template-release-notes.md
Labels: target/23.1

#3036 chore: automatically set the hilla version in the release notes
  scripts/generator/generate.js
  scripts/generator/templates/template-release-notes-maintenance.md
  scripts/generator/templates/template-release-notes-prerelease.md
  scripts/generator/templates/template-release-notes.md
Labels: target/23.1

#3040 chore: add new features section in release-notes [skip ci]
  scripts/generator/templates/template-release-notes.md
Labels: target/23.1

#3047 chore: Update MPR version to 6.0.1
  versions.json
Labels: target/23.0, target/23.1

#3084 chore: update spring boot to 2.7.1
  hilla-spring-boot-starter/pom.xml
  vaadin-spring-boot-starter/pom.xml
Labels: target/23.1
