Repository vaadin/platform, pull requests merged in 2022-10, with the labels that each got.

#3313 chore: update license-checker to 1.10.0
  versions.json
Labels: target/master

#3327 chore: update spring boot to 2.7.4
  hilla-spring-boot-starter/pom.xml
  vaadin-spring-boot-starter/pom.xml
Labels: target/23.2

#3344 chore: Update to latest license-checker
  versions.json
Labels: target/23.2, target/23.3

#3361 chore:update Jackson-databind to 2.13.4.2
  vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
Labels: target/23.2, target/23.3

#3046 !fix: Remove scope definition from testbench dependencies
  scripts/generator/templates/template-vaadin-spring-bom.xml
Labels: v24

#3414 chore: Update testbench to 8.1.2
  versions.json
Labels: target/23.2
