Repository vaadin/platform, pull requests merged in 2022-09, with the labels that each got.

#3255 chore: Upgrade to license checker 1.8.1
  versions.json
Labels: target/23.2

#3258 chore: update license-checker version to 1.8.1
  vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
Labels: target/23.2

#3261 chore: Upgrade to license checker 1.9.0
  versions.json
Labels: target/23.2

#3265 chore: Update testbench version
  versions.json
Labels: target/23.2

#3277 chore: Update Quarkus add-on version to 1.1.2
  versions.json
Labels: target/22.0, target/23.1, target/23.2

#3280 chore: Update spring boot version to 2.7.3
  hilla-spring-boot-starter/pom.xml
  vaadin-spring-boot-starter/pom.xml
Labels: target/23.1, target/23.2

#3288 chore: Update CDI add-on version to 14.0.1
  versions.json
Labels: target/23.1, target/23.2
