Repository vaadin/platform, pull requests merged in 2023-12, with the labels that each got.

#4754 get rid of unsupported versions for jandex-plugin
  vaadin-core-jandex/pom.xml
  vaadin-jandex/pom.xml
Labels: target/23.3, target/24.2, target/22.1, target/23.4

#4759 chore: update dependency to fix CVE-2023-6378
  vaadin-spring-boot-starter/pom.xml
Labels: target/23.3, target/24.2

#4777 chore: use logback-* 1.2.13 in V23.* [skip ci]
  scripts/generateAndCheckSBOM.js
  scripts/generator/templates/template-release-notes-maintenance.md
  vaadin-spring-boot-starter/pom.xml
Labels: target/23.4

#4776 chore: update logback-classic to 1.4.14 [skip ci]
  vaadin-spring-boot-starter/pom.xml
Labels: target/24.1, target/24.2

#4783 Upgrade Swing-kit to 2.2.2 [skip ci]
  versions.json
Labels: target/24.2

#4784 upgrade sso kit to 2.2.1 [skip ci]
  versions.json
Labels: target/24.1

#4731 chore : update dependency-check to use latest
  .github/workflows/sbom.yml
  scripts/generateAndCheckSBOM.js
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#4810 chore: Upgrade MPR to 2.2.20
  versions.json
Labels: target/14.11

#4809 chore: Upgrade MPR to 5.1.5
  versions.json
Labels: target/22.2

#4808 chore: Upgrade MPR to 6.1.11
  vaadin-platform-servlet-containers-tests/bnd-tools-test/app.bndrun
  vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
  versions.json
Labels: target/23.4

#4806 add the jackson-databind version to white list [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/24.1, target/24.2

#4831 chore: remove form-filler from exclude list [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/24.2, target/24.3

#4839 chore: Bump Copilot [skip ci]
  versions.json
Labels: target/24.3

#4841 upgrade classic component to 24.2.0 [skip ci]
  versions.json
Labels: target/24.2, target/24.3

#4845 update testbench to 8.2.5
  versions.json
Labels: target/23.4

#4851 chore: bump Testbench to 9.2.1
  versions.json
Labels: target/24.3

#4853 chore: Bump Copilot
  versions.json
Labels: target/24.3

#4860 chore: upgrade to springboot version to 3.2.1
  pom.xml
Labels: target/24.3

#4865 chore: Bump copilot
  versions.json
Labels: target/24.3

#4867 chore: fix infinite loop when running sbom script [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/24.2, target/23.4, target/24.3

#4872 sbom: remove unnecessary exclusion [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/23.3

#4874 chore: add vaadin-side-nav-testbench to testbench poms
  vaadin-testbench-junit5/pom.xml
  vaadin-testbench/pom.xml
Labels: target/24.2, target/24.3

#4876 test: remove feature flag for side-nav
  vaadin-platform-test/src/main/resources/vaadin-featureflags.properties
Labels: target/24.2, target/24.3
