Repository vaadin/platform, pull requests merged in 2023-10, with the labels that each got.

#4543 chore: Upgrade to TestBench 9.1.0.rc1
  versions.json
Labels: target/24.2

#4548 chore: Update versions.json with Form Filler RC1
  scripts/generateAndCheckSBOM.js
  versions.json
Labels: target/24.2

#4551 chore: update MPR to 7.0.8
  versions.json
Labels: target/24.1, target/24.2

#4560 disable bomber by default in sbom.yml [skip ci]
  .github/workflows/sbom.yml
  scripts/generateAndCheckSBOM.js
Labels: target/23.3, target/24.1, target/24.2

#4564 remove outdated tomcat exclusions
  vaadin-spring-boot-starter/pom.xml
Labels: target/24.2

#4567 Upgrade CE to 6.1.0.rc1
  versions.json
Labels: target/24.2

#4572 chore: Update TestBench to 9.1.0.rc2
  versions.json
Labels: target/main

#4574 chore: Upgrade to TestBench 9.1.0
  versions.json
Labels: target/24.2

#4580 chore: fix bomber flag again [skip ci]
  .github/workflows/sbom.yml
  scripts/generateAndCheckSBOM.js
Labels: target/23.3, target/24.1, target/24.2

#4593 Add appsec-kit to the BOM
  scripts/generateAndCheckSBOM.js
  scripts/generator/templates/template-vaadin-bom.xml
  vaadin-platform-sbom/pom.xml
  versions.json
Labels: target/24.2

#4598 chore: pass all parameters when there is a new version has been set [skip ci]
  .github/workflows/sbom.yml
Labels: target/main

#4604 update appsec kit to 3.0.0
  versions.json
Labels: target/24.2

#4606 chore: update spring-boot to 3.1.5
  pom.xml
Labels: target/24.1, target/24.2

#4610 chore: upgrade spring boot to 2.7.17 (22.1)
  vaadin-spring-boot-starter/pom.xml
Labels: target/14.10, target/14.11

#4614 update dependency+check plugin to 8.4.2 [skip ci]
  .github/workflows/sbom.yml
Labels: target/24.2

#4617 Remove not needed CVE exclusions [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/24.2

#4622 use form-filler 1.0.1 [skip ci]
  versions.json
Labels: target/main

#4632 update swing-kit to 2.2.1 [skip ci]
  versions.json
Labels: target/24.2

#4640 chore: add optional webpush library to sbom build file
  vaadin-platform-sbom/pom.xml
Labels: target/24.2

#4646 chore:upgrade jetty.version to resolve CVE-2023036479
  vaadin-platform-test/pom-bower.xml
  vaadin-platform-test/pom.xml
Labels: target/14.11
