Repository vaadin/platform, pull requests merged in 2023-02, with the labels that each got.

#3736 chore: add DSP to release note [skip ci]
  scripts/generator/templates/template-release-notes-maintenance.md
  scripts/generator/templates/template-release-notes-prerelease.md
  scripts/generator/templates/template-release-notes.md
Labels: target/23.3

#3769 chore: fix icons indexes [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/23.3

#3773 chore: fix sorting releases when snapshots or first release [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/23.3

#3778 chore: extract dependencies from vaadin/vaadin-core to new modules
  .gitignore
  pom.xml
  scripts/generateBoms.sh
  scripts/generator/templates/template-dev-bundle-pom.xml
  vaadin-core-internal/pom.xml
  vaadin-core-internal/src/test/java/VersionsFileTest.java
  vaadin-core/pom.xml
  vaadin-internal/pom.xml
  vaadin/pom.xml
Labels: target/master

#3783 chore: do not report twice if no alpha in branch [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/23.3, target/24.0

#3796 chore: remove the license checking file (23.3)
  vaadin-platform-test/src/test/java/com/vaadin/LicenseCheckTest.java
Labels: target/23.2

#3806 fix: Add spreadsheet to dev bundle
  scripts/generator/templates/template-dev-bundle-pom.xml
Labels: target/24.0

#3826 fix: Add PWA to the default bundle
  vaadin-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/DefaultDevBundleIT.java
Labels: target/24.0

#3828 chore: update license-checker to 1.12.0
  versions.json
Labels: target/23.2, target/23.3, target/24.0

#3829 chore: update TB to 9.0.0.rc1
  versions.json
Labels: target/24.0

#3837 fix: Use JNA 5.12.1 required by the license checker
  scripts/generator/templates/template-vaadin-bom.xml
Labels: target/23.3, target/24.0
