Repository vaadin/platform, pull requests merged in 2023-04, with the labels that each got.

#3984 chore: update license-checker to 1.12.3 (V14)
  scripts/generator/templates/template-vaadin-bom.xml
  versions.json
Labels: target/14.10

#4038 Update TB to 9.0.3
  versions.json
Labels: target/24.0

#4018 chore: use slf4j 1.7.x for Vaadin 14
  scripts/generator/templates/template-vaadin-bom.xml
  vaadin/pom.xml
Labels: target/14.10

#4021 chore: add one commercial component to gradle view
  vaadin-platform-gradle-test/build.gradle
  vaadin-platform-gradle-test/src/main/java/com/vaadin/platform/gradle/test/views/helloview/HelloVaadinerView.java
Labels: target/main, target/24.0

#4047 chore: force push sbom artifacts for release [skip ci]
  .github/workflows/sbom.yml
Labels: target/23.3, target/24.0

#4058 chore: update spring.boot to 3.0.6
  pom.xml
Labels: target/24.0

#4076 chore: Update flow-spring to 12.4.5
  versions.json
Labels: target/14.9, cherry-picked-14.9
