Repository vaadin/platform, pull requests merged in 2023-03, with the labels that each got.

#3866 fix: maven 3.8.2 and 3.8.3 are broken [skip ci]
  .github/workflows/pit.yml
Labels: target/23.2, target/23.3, target/24.0

#3850 Remove the common-fileupload dependency from osgi test module
  vaadin-platform-servlet-containers-tests/bnd-tools-test/pom.xml
Labels: target/24.0

#3874 chore: align spring dependencies with flow
  pom.xml
Labels: target/24.0

#3842 fix: Make vaadin depend on vaadin-core instead of vaadin-dev
  vaadin/pom.xml
Labels: target/24.0, cherry-picked-24.0

#3875 chore: add licenses and cve to whitelists
  scripts/generateAndCheckSBOM.js
Labels: target/24.0

#3881 chore: Exclude line-awesome from default dev-bundle
  vaadin-dev-bundle/frontend/themes/vaadin-dev-bundle/theme.json
Labels: target/main

#3876 chore: only use linux lib installation workaround in ACT [skip ci]
  .github/workflows/pit.yml
Labels: target/23.2, target/23.3, target/24.0

#3858 chore: update TB to 9.0.0
  versions.json
Labels: target/24.0, cherry-picked-24.0

#3888 chore: use spring-boot-bom for dependencies [skip ci]
  scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
Labels: target/24.0

#3887 chore: delete greetings workflow [skip ci]
  .github/workflows/greetings.yml
Labels: target/23.3, target/24.0

#3895 chore: Update to TestBench 9.0.1
  versions.json
Labels: target/24.0

#3897 chore: update dependencies for sbom.yml
  .github/workflows/sbom.yml
Labels: target/23.3, target/24.0

#3903 chore: provide the dependencies for javadoc generation [skip ci]
  scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
Labels: target/main

#3908 chore: inputs has a limit of 10 [skip ci]
  .github/workflows/pit.yml
Labels: target/23.3, target/24.0

#3913 fixes: provided jakarta-annotation-api dependency for javadoc [skip ci]
  scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
Labels: target/24.0

#3919 chore: Upgrade to TestBench 8.2.2
  versions.json
Labels: target/23.2

#3923 chore: Upgrade license-checker to 1.12.2
  scripts/generator/templates/template-vaadin-bom.xml
  versions.json
Labels: target/24.0

#3924 chore: update vaadin-development-mode-detector to 2.0.6
  versions.json
Labels: target/23.3, target/24.0

#3921 test: Ensure the dev bundle include usage statistics
  pom.xml
  scripts/generator/templates/template-dev-bundle-pom.xml
  vaadin-dev-bundle/src/test/java/com/vaadin/devbundle/BundleTest.java
Labels: target/24.0

#3929 chore: do not run tests in SBOM generation [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/23.2, target/23.3, target/24.0

#3939 chore: use snapshots when generating SBOM in PRs [skip ci]
  .github/workflows/sbom.yml
  scripts/generateAndCheckSBOM.js
Labels: target/23.2, target/23.3, target/24.0

#3947 chore: update router to 1.7.5 [skip ci]
  versions.json
Labels: target/24.0

#3962 chore: align property name with other projects [skip ci]
  hilla-spring-boot-starter/pom.xml
  pom.xml
  scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
  vaadin-platform-hybrid-test/pom-dev-mode.xml
  vaadin-platform-hybrid-test/pom.xml
  vaadin-spring-boot-starter/pom.xml
Labels: target/23.3, target/24.0

#3967 chore: Upgrade license checker to 1.12.3
  versions.json
Labels: target/24.0

#3968 chore: update spring-boot to 3.0.5 [skip ci]
  pom.xml
Labels: target/24.0

#3991 Revert "chore: Upgrade vcf-nav to 1.1.1 (#3989) (CP: 24.0)"
  vaadin-dev-bundle/src/main/java/com/vaadin/devbundle/FakeAppConf.java
Labels: target/24.0

#3988 chore: Update TB to 9.0.2
  versions.json
Labels: target/24.0

#4003 chore: fix regex [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/23.2, target/23.3, target/24.0
