Repository vaadin/platform, pull requests merged in 2023-09, with the labels that each got.

#4446 chore: upgrade spring boot 3.1.3 [skip ci]
  pom.xml
  vaadin-spring-boot-starter/pom.xml
Labels: target/24.1

#4494 chore: bump spring boot to 2.7.16 (cp:14.10)
  vaadin-spring-boot-starter/pom.xml
Labels: target/14.11

#4497 chore: upgrade spring-boot version to 3.1.4
  pom.xml
Labels: target/24.1

#4508 chore: Update form filler to beta
  scripts/generateAndCheckSBOM.js
  versions.json
Labels: need to pick manually

#4509 chore: update sso-kit to 2.2.0.beta1
  versions.json
Labels: need to pick manually

#4523 chore: bump vaadin-parent versiont o 2.2.1 [skip ci]
  pom.xml
Labels: target/24.2

#4526 chore:update plugin version (V14)
  vaadin-platform-test/pom-bower.xml
  vaadin-platform-test/pom.xml
Labels: target/14.11

#4527 chore: Update TestBench to 9.1.0.beta2
  versions.json
Labels: target/24.2

#4532 run gradle test in selenium hub
  vaadin-platform-gradle-test/src/test/java/com/vaadin/platform/gradle/test/AbstractPlatformTest.java
Labels: target/23.3, target/24.1, target/24.2, target/22.1
