Repository vaadin/platform, pull requests merged in 2023-08, with the labels that each got.

#4373 chore: test SBom run with latest suppression rule
  scripts/generateAndCheckSBOM.js
Labels: target/24.1

#4390 Update testbench to 9.0.6
  versions.json
Labels: target/24.1

#4398 chore: update TB to 9.0.7
  versions.json
Labels: target/24.0, target/24.1

#4413 Update mpr version to 7.0.7
  versions.json
Labels: target/24.0, target/24.1

#4416 Update mpr to 2.2.18
  versions.json
Labels: target/14.11
