Repository vaadin/platform, pull requests merged in 2023-06, with the labels that each got.

#4210 fix: update plugin versions
  scripts/generateAndCheckSBOM.js
  scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
Labels: target/24.1

#4222 chore: Add supported browsers to tests
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: cherry-picked-24.1

#4227 chore: remove the unnecessary body content with asset upload [skip ci]
  .github/workflows/sbom.yml
Labels: target/main, target/24.0, target/24.1

#4242 fix guava vulnerabilities CVE-2023-2976, CVE-2020-8908
  scripts/generateAndCheckSBOM.js
  vaadin-testbench/pom.xml
Labels: target/main, target/24.0

#4247 Update TB to latest
  versions.json
Labels: target/24.1

#4114 chore: added codestarts for vaadin-quarkus-extension
  vaadin-quarkus-extension/pom.xml
Labels: target/main, target/23.3, target/24.0

#4263 fix: Include CheckboxGroup in the eager bundle
  vaadin-prod-bundle/src/main/java/com/vaadin/prodbundle/EagerView.java
  vaadin-prod-bundle/src/test/java/com/vaadin/prodbundle/AllComponentsIncludedTest.java
Labels: target/24.1

#4267 chore: exclude jackson-databind alert [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/24.1

#4281 Update mpr version
  versions.json
Labels: target/24.0, target/24.1

#4299 chore: group platform modules in a profile, remove gradle module activation rule (CP: 24.1)
  hilla-dev/pom.xml
  hilla-react-spring-boot-starter/pom.xml
  hilla-react/pom.xml
  hilla-spring-boot-starter/pom.xml
  hilla/pom.xml
  pom.xml
  scripts/generator/templates/template-hilla-bom.xml
  scripts/generator/templates/template-servlet-containers-tests-pom.xml
  vaadin-platform-hybrid-test/pom.xml
  vaadin-platform-test/pom.xml
Labels: target/23.3, target/24.0

#4300 chore: upgrade sb to 3.1.1
  pom.xml
Labels: target/24.1

#4301 chore: group platform modules in a profile, remove gradle module activation rule (CP: 24.0)
  hilla-dev/pom.xml
  hilla-react/pom.xml
  hilla-spring-boot-starter/pom.xml
  hilla/pom.xml
  pom.xml
  scripts/generator/templates/template-hilla-bom.xml
  scripts/generator/templates/template-hilla-maven-plugin-pom.xml
  scripts/generator/templates/template-servlet-containers-tests-pom.xml
  vaadin-platform-hybrid-test/pom.xml
  vaadin-platform-test/pom.xml
Labels: target/23.3
