Repository vaadin/platform, pull requests merged in 2024-10, with the labels that each got.

#6867 chore: upgrade license-checker to 1.13.0
  versions.json
Labels: target/main

#6874 chore: bump vaadin-quarkus to 2.1.0.rc2
  versions.json
Labels: target/24.5

#6876 chore: bump flow-cdi to 15.1.0.rc1
  versions.json
Labels: target/24.5

#6878 move collaboration-engine to vaadin-core
  vaadin-core-internal/pom.xml
  vaadin-internal/pom.xml
Labels: target/24.5

#6873 chore: upgrade spring boot support version [skip ci]
  scripts/generator/templates/template-release-notes.md
Labels: target/24.5

#6892 chore: upgrade control-center to 1.0.0
  versions.json
Labels: target/main

#6921 chore: exclude flow artifacts from requireUpperBoundDeps enforcer rule [skip ci]
  vaadin/pom.xml
Labels: target/24.4, target/24.5

#6927 chore: upgrade springboot to 3.3.5
  pom.xml
Labels: target/24.5

#6926 chore: Remove ui-tests dependency
  scripts/generator/templates/template-release-notes-maintenance.md
  scripts/generator/templates/template-release-notes-prerelease.md
  scripts/generator/templates/template-release-notes.md
  scripts/generator/templates/template-vaadin-platform-javadoc-pom.xml
  scripts/generator/templates/template-vaadin-spring-bom.xml
  vaadin-dev/pom.xml
  versions.json
Labels: target/24.5
