Repository vaadin/platform, pull requests merged in 2024-08, with the labels that each got.

#6687 chore: upgrade springboot to 3.2.9 (24.4)
  pom.xml
  scripts/generateAndCheckSBOM.js
Labels: target/24.3

#6694 chore: always upload sbom report for release [skip ci]
  .github/workflows/sbom.yml
Labels: target/24.3, target/23.5, target/24.4

#6715 chore: chore: enable artifacts upload for manual use [skip ci]
  .github/workflows/sbom.yml
Labels: target/24.3, target/23.5

#6719 'chore: use version tag if exists'
  scripts/generateAndCheckSBOM.js
Labels: target/24.3, target/23.5, target/24.4
