Repository vaadin/platform, pull requests merged in 2024-05, with the labels that each got.

#5714 upgrade k8t kit to 2.2.2 [skip ci]
  versions.json
Labels: target/main

#5727 chore: upgrade detector to 2.0.7 [skip ci]
  versions.json
Labels: target/23.3, target/14.11, target/22.1, target/23.4, target/24.3, target/23.5, target/24.4

#5737 chore: update hilla to beta2
  versions.json
Labels: target/main

#5860 chore: remove old react-components entry
  versions.json
Labels: target/24.4

#6427 chore: refactor versions json
  scripts/generator/generate.js
  scripts/generator/src/creator.js
  scripts/generator/src/writer.js
  versions.json
Labels: target/24.4

#6444 update testbench to 9.3.0.beta2
  versions.json
Labels: target/24.4, cherry-picked-24.4

#6450 chore: upgrade spring.boot version to 3.2.6
  pom.xml
Labels: target/24.4

#6464 chore: update appsec-kit-starter to 3.2.0.beta1
  versions.json
Labels: target/main
