Repository vaadin/platform, pull requests merged in 2024-09, with the labels that each got.

#6751 chore: bump quarkus add-on to 2.0.2
  versions.json
Labels: target/24.3

#6759 chore: Upgrade LC to 1.12.14
  versions.json
Labels: target/14.11, target/24.3, target/23.5

#6776 chore: prevent jandex artifacts to import transitive dependencies
  vaadin-core-jandex/pom.xml
  vaadin-core-jandex/src/test/java/com/vaadin/jandex/JandexSmokeTest.java
  vaadin-jandex/pom.xml
  vaadin-jandex/src/test/java/com/vaadin/jandex/JandexSmokeTest.java
Labels: target/24.4

#6824 chore: upgrade to TB 9.3.5
  versions.json
Labels: target/24.4
