Repository vaadin/platform, pull requests merged in 2024-06, with the labels that each got.

#6474 chore: drop outdated featureflag
  vaadin-prod-bundle/src/main/resources/vaadin-featureflags.properties
Labels: target/24.4

#6510 chore: drop changeSince function [skip ci]
  scripts/generator/src/creator.js
Labels: target/main

#6519 feat: Property to disable hilla task registration
  scripts/generator/templates/template-vaadin-gradle-plugin-pom.xml
Labels: target/24.4

#6523 chore: upgrade license-checker to 1.12.13 [skip ci]
  versions.json
Labels: target/24.4

#6536 chore: disable bomber temporarily [skip ci]
  scripts/generateAndCheckSBOM.js
Labels: target/24.4

#6542 chore: upgrade form-filler to 1.1.1 [skip ci]
  versions.json
Labels: target/24.3, target/24.4
