Repository vaadin/platform, pull requests merged in 2024-11, with the labels that each got.

#6966 chore:fix link used in release note [skip ci]
  scripts/generator/templates/template-release-notes-maintenance.md
  scripts/generator/templates/template-release-notes-prerelease.md
  scripts/generator/templates/template-release-notes.md
Labels: target/24.4, target/24.5

#6977 chore: upgrade swing-kit to 2.3.0 [skip ci]
  versions.json
Labels: target/24.4, target/24.5

#6980 chore: upgrade kubernetes-kit 2.3.0 [skip ci]
  versions.json
Labels: target/24.4, target/24.5

#6984 upgrade sso-kit to 3.0.1 [skip ci]
  versions.json
Labels: target/24.4, target/24.5

#6998 fix: dependency convergence error from copilot
  vaadin-dev/pom.xml
  versions.json
Labels: target/24.4, target/24.5

#7020 chore: Update featurepack to 24.5.1 [skip ci]
  versions.json
Labels: target/24.5

#7031 chore: License Checker 1.13.2
  versions.json
Labels: v14.2, target/23.4, target/24.4, target/24.5
