Repository vaadin/platform, pull requests merged in 2025-06, with the labels that each got.

#7687 chore: upgrade testbench to 9.4.0.rc1
  versions.json
Labels: target/24.8

#7689 chore: update control-center to 1.3.0.beta2
  versions.json
Labels: target/24.8

#7703 chore: add name tag to gradle plugin portal module [skip ci]
  scripts/generator/templates/template-vaadin-gradle-plugin-portal-pom.xml
Labels: target/24.6, target/24.7, target/24.8

#7739 chore:add javadoc and source jar to maven-plugin (24.8) [skip ci]
  scripts/generator/templates/template-vaadin-maven-plugin-pom.xml
Labels: target/main, target/24.7

#7752 chore: upgrade springboot to 3.4.7
  pom.xml
Labels: target/24.6
