Repository vaadin/platform, pull requests merged in 2025-05, with the labels that each got.

#7571 workaround: use safari 17 for testing (23.6)
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/23.5

#7570 workaround: use safari 17 for testing (24.7)
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/24.6

#7572 workaround: use safari 17 for testing (14.13)
  vaadin-platform-test/src/test/java/com/vaadin/platform/test/ComponentsIT.java
Labels: target/14.12

#7605 chore: fix typo in test. (24.7) [skip ci]
  vaadin-platform-react-hybrid-security-test/src/main/frontend/views/@index.tsx
  vaadin-platform-react-hybrid-test/src/main/frontend/views/@index.tsx
Labels: target/main

#7607 chore: upgrade to TB 9.3.12 (24.7)
  versions.json
Labels: target/24.6

#7615 chore: upgrade vaadin-parent to 3.0.0
  pom.xml
Labels: target/23.5, target/24.6, target/24.7, target/23.6, target/14.12, target/14.13

#7632 chore: upgrade spring-boot to 3.5.0
  pom.xml
Labels: target/24.8

#7648 chore: Flow Quarkus 2.2.0.alpha1
  versions.json
Labels: target/24.8

#7656 chore: upgrade copilot to 24.8.0.alpha8
  versions.json
Labels: target/main

#7671 chore: upgrade control-center to 1.3.0.beta1 (24.8) [skip ci]
  scripts/generateAndCheckSBOM.js
  versions.json
Labels: target/main
