Repository vaadin/platform, pull requests merged in 2025-04, with the labels that each got.

#7496 chore: bump CC to 1.2.3
  versions.json
Labels: target/24.7

#7526 chore: TestBench 9.3.11
  versions.json
Labels: target/24.6

#7534 chore: upgrade Kubernetes-kits to 2.4.2 [skip ci]
  versions.json
Labels: target/24.6, target/24.7

#7544 chore: upgrade springboot to 3.4.5
  pom.xml
Labels: target/24.6, cherry-picked-24.6, target/24.7, cherry-picked-24.7

#7564 chore: upgrade sso to 3.1.1 [skip ci]
  versions.json
Labels: target/24.6, target/24.7
