Repository vaadin/platform, pull requests merged in 2025-03, with the labels that each got.

#7392 chore: bump vaadin-quarkus to 2.1.2
  versions.json
Labels: target/24.5, target/24.6, target/24.7

#7418 chore: upgrade feature-pack to 24.7.0.rc1
  versions.json
Labels: target/24.7

#7422 chore: upgrade control-center to 1.2.0.rc1 [skip ci]
  versions.json
Labels: target/main

#7447 chore: upgrade control-center to 1.2.0 [skip ci]
  versions.json
Labels: target/main

#7450 chore: upgrade feature-pack to 24.7.0 [skip ci]
  versions.json
Labels: target/main
