Repository vaadin/platform, pull requests merged in 2025-07, with the labels that each got.

#7804 fix: add proper deployment module for quarkus extension (24.8)
  .gitignore
  pom.xml
  scripts/generateBoms.sh
  scripts/generator/generate.js
  scripts/generator/templates/template-vaadin-quarkus-pom.xml
  vaadin-quarkus/vaadin-quarkus-extension-deployment/pom.xml
  vaadin-quarkus/vaadin-quarkus-extension/pom.xml
  vaadin-quarkus/vaadin-quarkus-extension/scripts/MetaDataReplacements.java
Labels: target/main, target/24.7, target/24.9

#7815 chore: bump vaadin-quarkus to 2.2.1 (24.8)
  versions.json
Labels: target/24.9

#7824 chore: sso 3.1.2
  versions.json
Labels: target/24.8, target/24.9

#7868 chore: upgrade TB to 9.4.2
  versions.json
Labels: target/24.9

#7874 Chore: Update Collaboration Kit to 6.5.0
  versions.json
Labels: target/main, target/24.9
